### ISSUE TITLE
[feature] buat crud alumni

### ISSUE THREAD

**Issue by ibnumardini** [ibnumardini/simalu#2]
## Skema tabel
![image](https://github.com/user-attachments/assets/3c8da2c0-25b6-4fa9-82d3-07298b135f66)

## Deskripsi task
- Buat page pada menu `/alumnis`
- Goal dari task ini adalah buat halaman untuk bisa create, read (show), update, delete, untuk pembatasan siapa yang bisa crud di kesampingkan dulu, sekarang semuanya bisa manipulasi data alumni.

## Referensi
- Halaman alumni bisa mengikuti struktur format yang sudah ada, cek di menu `view/dashboard/pages`

**Comment by wardanaricho** [comment]
halo bang, untuk alur crud alumni kek gimana bang? habis register akun terus buat data alumni untuk diri sendiri kah? atau kek gimana bang hehe,

**Comment by ibnumardini** [comment]
> halo bang, untuk alur crud alumni kek gimana bang? habis register akun terus buat data alumni untuk diri sendiri kah? atau kek gimana bang hehe,

Haloo bang, dah di update untuk deskripisi tasknya ya bang 👌, oiya untuk diskusi lebih lanjut bisa join aja di discord [simalu](https://discord.gg/FnHMcUYF) ya bang, bisa lebih enak diskusinya.

**Comment by wardanaricho** [comment]
Siap bang
